# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Roman Klyuev

"""Storage foundation for SQLite-backed plan manager."""

from plan_manager.storage.db import (
    DB_FILENAME,
    StartupAction,
    StartupDecision,
    StorageBootstrapError,
    bootstrap,
    decide_startup_action,
    startup_storage,
)
from plan_manager.storage.importer import (
    ImportProblem,
    ImportReport,
    LegacyImportError,
    import_legacy_tree,
)
from plan_manager.storage.repositories import (
    EventRecord,
    PlanStateRecord,
    TaskStatusTransitionConflictError,
    append_event,
    create_plan,
    create_story,
    create_task,
    delete_plan,
    delete_story,
    delete_task,
    get_plan,
    get_plan_state,
    get_story,
    get_task,
    list_events,
    list_plans,
    list_stories,
    list_tasks,
    set_current_story,
    set_current_task,
    transition_task_status_guarded,
    update_plan,
    update_story,
    update_task,
)
from plan_manager.storage.schema import LATEST_USER_VERSION, apply_migrations
from plan_manager.storage.uow import (
    DEFAULT_BUSY_RETRY_ATTEMPTS,
    DEFAULT_BUSY_TIMEOUT_MS,
    StorageBusyError,
    canonical_utc_timestamp,
    unit_of_work,
)

__all__ = [
    "DB_FILENAME",
    "DEFAULT_BUSY_RETRY_ATTEMPTS",
    "DEFAULT_BUSY_TIMEOUT_MS",
    "LATEST_USER_VERSION",
    "EventRecord",
    "ImportProblem",
    "ImportReport",
    "LegacyImportError",
    "PlanStateRecord",
    "StartupAction",
    "StartupDecision",
    "StorageBootstrapError",
    "StorageBusyError",
    "TaskStatusTransitionConflictError",
    "append_event",
    "apply_migrations",
    "bootstrap",
    "canonical_utc_timestamp",
    "create_plan",
    "create_story",
    "create_task",
    "decide_startup_action",
    "delete_plan",
    "delete_story",
    "delete_task",
    "get_plan",
    "get_plan_state",
    "get_story",
    "get_task",
    "import_legacy_tree",
    "list_events",
    "list_plans",
    "list_stories",
    "list_tasks",
    "set_current_story",
    "set_current_task",
    "startup_storage",
    "transition_task_status_guarded",
    "unit_of_work",
    "update_plan",
    "update_story",
    "update_task",
]
